### ISSUE TITLE
Encoding issue(?) with whitespace characters

### ISSUE THREAD

**Issue by rombert** [apache/incubator-ponymail#265]
Note the email at https://lists.apache.org/thread.html/52ecda6f7b859fa9cdd4d9fb64d6f7a3b54f29f971e5536e844d9150@%3Cdev.johnzon.apache.org%3E displays some weird characters instead of whitespace.

I've attached below the message as stored by my MUA after sending. The {{X-Evolution-}} headers can be ignored, they should not be in the final message.

[Using_johnzon-core_in_an_OSGi_container.txt](https://github.com/apache/incubator-ponymail/files/610162/Using_johnzon-core_in_an_OSGi_container.txt)

**Comment by sebbASF** [comment]
The character is a non-breaking space (\xa0) which is not being correctly handled by the archiver. It then gets substituted by the standard error replacement character which is what you are seeing.

However mod_mbox handles this OK [1], as does import-mbox when I tried re-importing the mbox files locally.

Most of the code is the same, except for the way they read the input for parsing.
Looks like there is an issue with the way the archiver handles standard input.

[1] http://mail-archives.apache.org/mod_mbox/johnzon-dev/201611.mbox/%3C1479940647.31291.1.camel%40apache.org%3E

**Comment by sebbASF** [comment]
Note that the Source version [2] of the message is also mangled in lists.a.o; it includes other odd characters (not the replacement char).

I tried parsing the input using 
msg = email.message_from_bytes(sys.stdin.buffer.read())
instead of
input_stream = io.TextIOWrapper(sys.stdin.buffer, encoding='utf-8', errors="ignore")
msgstring = input_stream.read()
msg = email.message_from_string(msgstring)

That fixes the display problem, however the source message then uses Base64 encoding for the body, which is not ideal as it cannot be read directly. It looks like the source problem is caused by using message.as_string() to re-create the source from the parsed mail. That may be to do with the original having been 8-bit.

[2] https://lists.apache.org/api/source.lua/52ecda6f7b859fa9cdd4d9fb64d6f7a3b54f29f971e5536e844d9150@%3Cdev.johnzon.apache.org%3E
