### ISSUE TITLE
lists.apache.org ponymail failing login using google oauth; failing with apache due to invalid username.

### ISSUE THREAD

**Issue by jcalcote** [apache/incubator-ponymail#500]
Failing to login to https://lists.apache.org/list.html?user@jclouds.apache.org

With Google oauth:
![image](https://user-images.githubusercontent.com/49394/61820068-87f26e80-ae11-11e9-97ce-4288e89cb9b8.png)

With apache oauth:
![image](https://user-images.githubusercontent.com/49394/61820142-aeb0a500-ae11-11e9-9140-de6ca69d0744.png)

Login is failing using google oauth due to some back-end oauth issue. Login is failing using apache oauth because my apache username is my email address and ponymail seems to think usernames should not have dots or at signs in them.

I have no way to login now. Please help. Note that since there are NO messages in the jclouds user list since mid-june, I'm guessing everyone else is having this trouble also. Good way to keep people from complaining about your product - keep them from logging into your help forum.

**Comment by sebbASF** [comment]
Apache user ids do not have '.' in them (and are not email addresses), so perhaps you are using the wrong login.

**Comment by jcalcote** [comment]
I used my email address to log into issues.apache.org. worked just fine.

**Comment by sebbASF** [comment]
issues.apache.org currently has its own independent authentication scheme.

PonyMail has two auth schemes: Google, and Apache.
For Apache auth you need to be an Apache committer with an Apache user id.

However, you don't need to use PonyMail in order to send an email to public ASF mailing lists, nor do you need to login to see the public lists.

See http://jclouds.apache.org/
in particular:
http://jclouds.apache.org/community/
and
http://jclouds.apache.org/reference/report-a-bug/
